### ISSUE TITLE
CosmosDb TransactionalBatch limitations

### ISSUE THREAD

**Issue by christianhelle** [atc-net/atc-cosmos-eventstore#39]
Persisting a large batch of events in a single command throws an exception that doesn't clearly explain why the operation failed

**CosmosDb Transactional batch operation limitations**
Currently, there are two known limits:
- The Azure Cosmos DB request size limit constrains the size of the TransactionalBatch payload to not exceed 2 MB, and the maximum execution time is 5 seconds.
- There's a current limit of 100 operations per TransactionalBatch to ensure the performance is as expected and within SLAs.

**Expected behavior**
Throw a more concrete error message in a specialized exception type would be the preferred way to describe why the operation failed

**Comment by LarsSkovslund** [comment]
Good catch @christianhelle.

There are two distinct parts to this library, the CQRS implementation and the underlying event store implementation.

**EventStore**
Should be limited to accept a maximum of 50 events + the metadata, just to be on the safe side. It would not be feasible to calculate/estimate payload size.

**CQRS**
Imposing a limit of one event per command is too strict as there are many valid use-cases for adding one or more events but at the same time it is consider bad design if a single command needs to write many events at once. When limit is exceeded, an exception needs to be thrown, clearly indicating an illegal operation is in progress. When applying events from a command handler, using `CommandContext.AddEvent` would be the most suitable place to enforce this, providing a callstack that will clearly indicate where the problem is. Allowing a maximum of 10 events should cover most use-cases.
